# frozen_string_literal: true

# rubocop:disable Lint/RedundantCopDisableDirective, Layout/LineLength, Layout/HeredocIndentation

module Engine
  module Config
    module Game
      module G18Scotland
        JSON = <<-'DATA'
{
   "filename":"18_scotland",
   "modulename":"18Scotland",
   "currencyFormatStr":"£%d",
   "bankCash":12000,
   "certLimit":{
      "2":25,
      "3":20,
      "4":16,
      "5":13,
      "6":11
   },
   "startingCash":{
      "2":1200,
      "3":800,
      "4":600,
      "5":480,
      "6":400
   },
   "capitalization":"full",
   "layout":"pointy",
   "mustSellInBlocks":false,
   "locationNames":{
      "A2":"Kyle of Lochalsh",
      "B3":"Mallaig",
      "B5":"Oban",
      "C4":"Fort William",
      "C10":"Stranraer",
      "D7":"Wemyss Bay",
      "E8":"Ayr",
      "F7":"Glasgow",
      "G2":"Inverness",
      "G6":"Stirling",
      "G10":"Dumfries",
      "H5":"Perth",
      "H7":"Falkirk",
      "I6":"Kirkcaldy",
      "J5":"Dundee",
      "J7":"Edinburgh",
      "K4":"Montrose",
      "K8":"Tweekbank",
      "K10":"Carlisle",
      "L3":"Aberdeen",
      "L7":"Dunbar",
      "L9":"Newcastle upon Tyne",
      "M8":"Newcastle upon Tyne"
   },
   "tiles":{
      "3":3,
      "4":6,
      "5":3,
      "6":3,
      "7":7,
      "8":18,
      "9":18,
      "57":7,
      "58":4,
      "12":2,
      "13":2,
      "14":6,
      "15":6,
      "16":1,
      "17":1,
      "18":1,
      "19":1,
      "20":1,
      "23":4,
      "24":4,
      "25":3,
      "26":2,
      "27":2,
      "28":2,
      "29":2,
      "30":2,
      "31":2,
      "59":3,
      "619":2,
      "141":1,
      "142":1,
      "143":1,
      "144":1,
      "205":2,
      "206":2,
      "39":2,
      "40":2,
      "41":2,
      "42":2,
      "43":2,
      "44":2,
      "45":2,
      "46":2,
      "47":4,
      "63":5,
      "64":1,
      "65":1,
      "66":1,
      "67":1,
      "68":1,
      "70":2,
      "448":2,
      "611":4,
      "G1":{
         "count":1,
         "color":"yellow",
         "code":"city=revenue:40,slots:1;city=revenue:40,slots:1;path=a:2,b:_0;path=a:3,b:_0;path=a:5,b:_1;path=a:0,b:_1;label=G"
      },
      "G2":{
         "count":1,
         "color":"green",
         "code":"city=revenue:60,slots:1;city=revenue:60,slots:1;city=revenue:60,slots:1;path=a:2,b:_0;path=a:3,b:_0;path=a:5,b:_1;path=a:1,b:_2;path=a:4,b:_2;path=a:0,b:_1;label=G"
      },
      "G3":{
         "count":1,
         "color":"brown",
         "code":"city=revenue:80,slots:1;city=revenue:80,slots:1;city=revenue:80,slots:2;path=a:2,b:_0;path=a:3,b:_0;path=a:5,b:_1;path=a:1,b:_2;path=a:4,b:_2;path=a:0,b:_1;label=G"
      },
      "E1":{
         "count":1,
         "color":"yellow",
         "code":"city=revenue:40,slots:1;city=revenue:40,slots:1;path=a:1,b:_0;label=E"
      },
      "E2":{
         "count":1,
         "color":"green",
         "code":"city=revenue:50,slots:1;city=revenue:50,slots:1;path=a:1,b:_0;path=a:4,b:_1;label=E"
      },
      "E3":{
         "count":1,
         "color":"brown",
         "code":"city=revenue:60,slots:2;city=revenue:60,slots:1;path=a:0,b:_0;path=a:1,b:_0;path=a:4,b:_1;label=E"
      }
   },
   "market":[
      [
         "75",
         "80",
         "90",
         "100p",
         "110",
         "125",
         "140",
         "155",
         "175",
         "200",
         "225",
         "255",
         "285",
         "315",
         "350"
      ],
      [
         "70",
         "75",
         "80",
         "90p",
         "100",
         "110",
         "125",
         "140",
         "155",
         "175",
         "200",
         "225",
         "255",
         "285",
         "315"
      ],
      [
         "65",
         "70",
         "75",
         "80p",
         "90",
         "100",
         "110",
         "125",
         "140",
         "155",
         "175",
         "200"
      ],
      [
         "60",
         "65",
         "70",
         "75p",
         "80",
         "90",
         "100",
         "110",
         "125",
         "140"
      ],
      [
         "55",
         "60",
         "65",
         "70p",
         "75",
         "80",
         "90",
         "100"
      ],
      [
         "50y",
         "55",
         "60",
         "65p",
         "70",
         "75",
         "80"
      ],
      [
         "45y",
         "50y",
         "55",
         "60",
         "65",
         "70"
      ],
      [
         "40y",
         "45y",
         "50y",
         "55",
         "60"
      ],
      [
         "30o",
         "40y",
         "45y",
         "50y"
      ],
      [
         "20o",
         "30o",
         "40y",
         "45y"
      ],
      [
         "10o",
         "20o",
         "30o",
         "40y"
      ]
   ],
   "companies":[
      {
         "name":"Private Company 1",
         "value":20,
         "revenue":5,
         "desc":"No special ability (yet!).",
         "sym":"P1"
      },
      {
         "name":"Private Company 2",
         "value":30,
         "revenue":5,
         "desc":"No special ability (yet!).",
         "sym":"P2"
      },
      {
         "name":"Private Company 3",
         "value":40,
         "revenue":10,
         "desc":"No special ability (yet!).",
         "sym":"P3"
      },
      {
         "name":"Private Company 4",
         "value":50,
         "revenue":15,
         "desc":"No special ability (yet!).",
         "sym":"P4"
      },
      {
         "name":"Private Company 5",
         "value":60,
         "revenue":15,
         "desc":"No special ability (yet!).",
         "sym":"P5"
      }
   ],
   "corporations":[
      {
         "float_percent":60,
         "sym":"AR",
         "name":"A Corporation",
         "logo":"system_18/A",
         "tokens":[
            0,
            40,
            100,
            100
         ],
         "coordinates":"F7",
         "color":"#ED1C24"
      },
      {
         "float_percent":60,
         "sym":"BR",
         "name":"B Corporation",
         "logo":"system_18/B",
         "tokens":[
            0,
            40,
            100,
            100
         ],
         "coordinates":"J7",
         "color":"#F9A01B"
      },
      {
         "float_percent":60,
         "sym":"CR",
         "name":"C Corporation",
         "logo":"system_18/C",
         "tokens":[
            0,
            40,
            100,
            100
         ],
         "coordinates":"L3",
         "color":"#FFF200",
         "text_color":"#000000"
      },
      {
         "float_percent":60,
         "sym":"DR",
         "name":"D Corporation",
         "logo":"system_18/D",
         "tokens":[
            0,
            40,
            100,
            100
         ],
         "coordinates":"J5",
         "color":"#00A651"
      },
      {
         "float_percent":60,
         "sym":"ER",
         "name":"E Corporation",
         "logo":"system_18/E",
         "tokens":[
            0,
            40,
            100,
            100
         ],
         "coordinates":"I6",
         "color":"#4AC8F5"
      },
      {
         "float_percent":60,
         "sym":"FR",
         "name":"F Corporation",
         "logo":"system_18/F",
         "tokens":[
            0,
            40,
            100,
            100
         ],
         "coordinates":"E8",
         "color":"#6D92CB"
      },
      {
         "float_percent":60,
         "sym":"GR",
         "name":"G Corporation",
         "logo":"system_18/G",
         "tokens":[
            0,
            40,
            100,
            100
         ],
         "coordinates":"H5",
         "color":"#B11F8E"
      },
      {
         "float_percent":60,
         "sym":"HR",
         "name":"H Corporation",
         "logo":"system_18/H",
         "tokens":[
            0,
            40,
            100,
            100
         ],
         "coordinates":"G2",
         "color":"black"
      }
   ],
   "trains":[
      {
         "name":"2",
         "distance":2,
         "price":80,
         "rusts_on":"4",
         "num":6
      },
      {
         "name":"3",
         "distance":3,
         "price":180,
         "rusts_on":"6",
         "num":5
      },
      {
         "name":"4",
         "distance":4,
         "price":300,
         "rusts_on":"D",
         "num":4
      },
      {
         "name":"5",
         "distance":5,
         "price":450,
         "num":3,
         "events":[
            {
               "type":"close_companies"
            }
         ]
      },
      {
         "name":"6",
         "distance":6,
         "price":630,
         "num":2
      },
      {
         "name":"D",
         "distance":999,
         "price":1100,
         "num":20,
         "available_on":"6",
         "discount":{
            "4":300,
            "5":300,
            "6":300
         }
      }
   ],
   "hexes":{
      "white":{
         "":[
            "A4",
            "B1",
            "B7",
            "C2",
            "C6",
            "D1",
            "D3",
            "D5",
            "D9",
            "E2",
            "E4",
            "E6",
            "E10",
            "F3",
            "F5",
            "F9",
            "G4",
            "G8",
            "H3",
            "H9",
            "I2",
            "I4",
            "I8",
            "J1",
            "J3",
            "J9",
            "K2",
            "L1",
            "M2"
         ],
         "city=revenue:0":[
            "L3",
            "C4",
            "B5",
            "J5",
            "D7",
            "E8",
            "C10",
            "G10"
         ],
         "town=revenue:0":[
            "A2",
            "B3",
            "K4",
            "G6",
            "L7",
            "K8"
         ],
         "city=revenue:0;label=G":[
            "F7"
         ],
         "city=revenue:0;label=E;border=edge:2,type:impassable":[
            "J7"
         ],
         "border=edge:4,type:impassable;border=edge:5,type:impassable":[
            "F1"
         ],
         "border=edge:1,type:impassable":[
            "H1"
         ],
         "town=revenue:0;border=edge:3,type:impassable":[
            "H7"
         ],
         "city=revenue:0;border=edge:0,type:impassable;border=edge:5,type:impassable":[
            "I6"
         ]
      },
      "yellow":{
         "city=revenue:0;city=revenue:0;label=OO":[
            "H5"
         ],
         "city=revenue:0;city=revenue:0;label=OO;border=edge:2,type:impassable":[
            "G2"
         ]
      },
      "red":{
         "offboard=revenue:yellow_30|brown_60|diesel_100;path=a:2,b:_0":[
            "M8",
            "L9",
            "K10"
         ]
      }
   },
   "phases":[
      {
         "name":"2",
         "train_limit":4,
         "tiles":[
            "yellow"
         ],
         "operating_rounds":1
      },
      {
         "name":"3",
         "on":"3",
         "train_limit":4,
         "tiles":[
            "yellow",
            "green"
         ],
         "operating_rounds":2,
         "status":[
            "can_buy_companies"
         ]
      },
      {
         "name":"4",
         "on":"4",
         "train_limit":3,
         "tiles":[
            "yellow",
            "green"
         ],
         "operating_rounds":2,
         "status":[
            "can_buy_companies"
         ]
      },
      {
         "name":"5",
         "on":"5",
         "train_limit":2,
         "tiles":[
            "yellow",
            "green",
            "brown"
         ],
         "operating_rounds":3
      },
      {
         "name":"6",
         "on":"6",
         "train_limit":2,
         "tiles":[
            "yellow",
            "green",
            "brown"
         ],
         "operating_rounds":3
      },
      {
         "name":"D",
         "on":"D",
         "train_limit":2,
         "tiles":[
            "yellow",
            "green",
            "brown"
         ],
         "operating_rounds":3
      }
   ]
}
        DATA
      end
    end
  end
end

# rubocop:enable Lint/RedundantCopDisableDirective, Layout/LineLength, Layout/HeredocIndentation
